### ISSUE TITLE
Stackage nightly build failure

### ISSUE THREAD

**Issue by lwm** [dylex/postgresql-typed#4]
```

Database/PostgreSQL/Typed/Types.hs:97:1: error:
    Failed to load interface for <E2><80><98>PostgreSQL.Binary.Decoder<E2><80><99>
    Perhaps you meant
      PostgreSQL.Binary.Decoding (from postgresql-binary-0.12.1)
      PostgreSQL.Binary.Encoding (from postgresql-binary-0.12.1)
      PostgreSQL.Binary.Prelude
    Use -v to see a list of the files searched for.

Database/PostgreSQL/Typed/Types.hs:98:1: error:
    Failed to load interface for <E2><80><98>PostgreSQL.Binary.Encoder<E2><80><99>
    Perhaps you meant
      PostgreSQL.Binary.Encoding (from postgresql-binary-0.12.1)
      PostgreSQL.Binary.Decoding (from postgresql-binary-0.12.1)
      PostgreSQL.Binary.Inet
    Use -v to see a list of the files searched for.
```

**Comment by dylex** [comment]
This was caused by postgresql-binary 0.12.  Added an upper bound on the dependency in hackage.  Building against 0.10 works.  Will add support for 0.12 in the next release.

**Comment by dylex** [comment]
Fixed in 0.5.1: builds with postgresql-binary 0.12 or older.

**Comment by lwm** [comment]
Thanks!
