### ISSUE TITLE
fails to build with crypton-1.1 and ram

### ISSUE THREAD

**Issue by juhp** [dylex/postgresql-typed#38]
```
       Building library for postgresql-typed-0.6.2.5...
       [ 1 of 17] Compiling Database.PostgreSQL.Typed.ErrCodes
       [ 2 of 17] Compiling Database.PostgreSQL.Typed.SQLToken
       [ 3 of 17] Compiling Database.PostgreSQL.Typed.Types
       [ 4 of 17] Compiling Database.PostgreSQL.Typed.Range
       [ 5 of 17] Compiling Database.PostgreSQL.Typed.Inet
       [ 6 of 17] Compiling Database.PostgreSQL.Typed.Dynamic
       [ 7 of 17] Compiling Database.PostgreSQL.Typed.Protocol
       /home/curators/work/unpack-dir/unpacked/postgresql-typed-0.6.2.5-2695797410afc1f7753baef321cbd1333bb58d6bfb2f77424a92745107574bb7/Database/PostgreSQL/Typed/Protocol.hs:418:7: error: [GHC-39999]
           • No instance for ‘memory-0.18.0:Data.ByteArray.Types.ByteArrayAccess
                                (Hash.Digest Hash.MD5)’
               arising from a use of ‘BA.convertToBase’
           • In the first argument of ‘(.)’, namely
               ‘BA.convertToBase BA.Base16’
             In the expression:
               BA.convertToBase BA.Base16
                 . (Hash.hash :: BSC.ByteString -> Hash.Digest Hash.MD5)
             In an equation for ‘md5’:
                 md5
                   = BA.convertToBase BA.Base16
                       . (Hash.hash :: BSC.ByteString -> Hash.Digest Hash.MD5)
           |
       418 | md5 = BA.convertToBase BA.Base16 . (Hash.hash :: BS.ByteString -> Hash.Digest Hash.MD5)
           |       ^^^^^^^^^^^^^^^^
```

**Comment by dylex** [comment]
Resolved in 0.6.2.6 by an optional `ram` flag, disabled by default, without which constrained to crypton < 1.1.
